### ISSUE TITLE
Update and remove activities services by entity id

### ISSUE THREAD

**Issue by j9brown** [pathofleastresistor/activity-manager#2]
Given that the integration creates new entities for each activity, I think it might make sense for the update and remove services to act on those entities instead of searching for an activity by category and name.

Bonus: It might also be useful for the add activity service to accept an optional entity id to use for the new activity instead of the automatically generated one.  Explicitly specifying the entity id when creating an activity would decouple the identity of the activity from its human-readable label and it opens up additional UI possibilities such as renaming activities (without changing their id).  Decoupling could also help to disambiguate situations where multiple activities with the same name have been created.

**Comment by pathofleastresistor** [comment]
I'm open to considering this as I think about a full management experience for activities.

**Comment by pathofleastresistor** [comment]
Added - https://github.com/pathofleastresistor/activity-manager/pull/12

The next release will be a breaking change where service calls will have to us entity_id.

**Comment by pathofleastresistor** [comment]
Closing this as this is now fully supported.
