### ISSUE TITLE
No info provided for what to enter during installation

### ISSUE THREAD

**Issue by sparkydave1981** [pathofleastresistor/activity-manager#4]
When adding the Integration in the HA settings area you get the below popup but there is nothing to say what we should enter here, nor is it in the docs.

It would be helpful if both the docs could be updated and also to include a short comment on this popup to say what sort of info is expected.

![image](https://github.com/pathofleastresistor/activity-manager/assets/7628509/d8cc29bb-253c-49af-95da-95f650a867c5)

Is this supposed to be the name of the first activity we want to track?

**Comment by pathofleastresistor** [comment]
Thanks for flagging this @sparkydave1981. As of right now it doesn't actually doesn't matter what you put there. I haven't found a way to get the integration to work without asking for something though. 

I will update the documentation for now and hopefully apply a proper fix in the future.

**Comment by pathofleastresistor** [comment]
0.0.4 removes the need for the text.
