### ISSUE TITLE
Time unit selection and other suggestions

### ISSUE THREAD

**Issue by FragMenthor** [pathofleastresistor/activity-manager#5]
Hello! And first of all, thanks for your work.
I stumbled across this integration and it seamed to fill one of my ocasional needs: kid's medication when they are sick, that normally occours every 8h, counting from the time of the last one. But I think this only works for days, right? (Setting to 0.3 days resulted in a value of frequency=0)
Could it be possible to define the **time unit** and the **amount**?
Also, If I want to send a reminder 10 minutes before, how can I do that? I could do a template, maybe. But would it be possible to add to the _**attibutes**_, one with the _**remaing time**_ (in seconds for instance, that should be the base; negative if overdue)? This would help automations, conditional cards and others, without adding extra template sensors or custom templates. Would be very usefull.
Also, the entities do not appear under the integration, it would be easier to manage if they did.
Just some suggestions / requests if possible, and **THANKS for doing this!**

**Comment by pathofleastresistor** [comment]
> I stumbled across this integration and it seamed to fill one of my ocasional needs: kid's medication when they are sick, that normally occours every 8h, counting from the time of the last one

0.0.4 now supports setting days, hours, minutes, seconds, so you can have an activity that's every 8 hours. 

> Also, the entities do not appear under the integration, it would be easier to manage if they did.
0.0.5-beta is moving to sensor attributes that are linked to the integration

> But would it be possible to add to the attibutes, one with the remaing time
For now it would be a template. Before I support remaining time, I need to figure out how to make sure I don't spam the database, so for a future release.

**Comment by pathofleastresistor** [comment]
Closing this out since most of the feedback has been integrated. Please open new issues if you have specific feedback or issues.
